#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=compare_models
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=4:00:00
#SBATCH --output=jobs/outputs/evaluate_game_%j.out

set -eo pipefail

module purge
module load 2025
module load Anaconda3/2025.06-1

cd "$HOME/Project_AI/"

mkdir -p jobs/outputs

echo "============================================================"
echo "Activating project venv"
echo "============================================================"

# Activate environment
export GEOTIFF_CSV="${GEOTIFF_CSV:-}"
set +u
source activate streetview
set -u
pip install cartopy

# ============================================================
# MODEL COMPARISON CONFIG
# ============================================================

python scripts/evaluation/evaluate_game_images.py \
    --game-dir data/Game1 \
    --checkpoint-both checkpoints/stage3_joint_latefusion/stage3_joint_both_scratchgeo_dim256_pos_latefusion_2.5ct_0.01gatereg \
    --checkpoint-concept checkpoints/stage3_joint_latefusion/stage3_joint_concept_only_scratchgeo_dim256_pos_latefusion_2.5ct_0gatereg \
    --concept-data-dir data/concept_data_v2 \
    --cached-dir /scratch-shared/igodzwon/Project_AI/data/6921d7831744c5356b098bf7_balanced/cached_streetclip_v2 \
    --output-dir results/game_evaluation