#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=jobs/outputs/test/test_script_smaller.log

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/Project_AI/

source activate streetview

python scripts/evaluation/evaluate_test_set.py \
    --sae-path "checkpoints/sae_smaller/best_sae.pth" \
    --test-csv "data/6921d7831744c5356b098bf7_balanced/splits/dataset_test.csv"
