#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=ca
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=4:00:00
#SBATCH --output=jobs/outputs/train_concept_aware.log

# Load modules
module load 2025
module load Anaconda3/2025.06-1
module load CUDA/12.8.0

# Activate environment
source activate streetview_pnair
export PYTHONNOUSERSITE=1

cd /scratch-shared/pnair/Project_AI/
export PYTHONPATH=/scratch-shared/pnair/Project_AI:$PYTHONPATH

# Run training
python scripts/training/train_concept_aware.py \
    --encoder_model "geolocal/StreetCLIP" \
    --batch_size 12 \
    --epochs 20 \
    --lr 3e-4 \
    --weight_decay 0.1 \
    --lambda_divergence 0.05 \
    --lambda_concept 1.0 \
    --label_smoothing 0.1 \
    --early_stopping_patience 5 \
    --save_interval 5 \
    --use_wandb \
    --country_filter "India" \
    --coordinate_loss_type "haversine" \


