#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=cgeo
#SBATCH --output=/scratch-shared/pnair/Project_AI/jobs/outputs/train_concept_aware.log
#SBATCH --time=7:00:00
#SBATCH --cpus-per-task=9
#SBATCH --mem=32G

# Activate environment
module load 2025
module load Anaconda3/2025.06-1
cd /scratch-shared/pnair/Project_AI/
module load CUDA/12.8.0

source activate streetview_pnair
export PYTHONNOUSERSITE=1
export PYTHONPATH=/scratch-shared/pnair/Project_AI:$PYTHONPATH

# Run Training with Concept-Aware configuration (CBM Architecture)
python scripts/training/train_concept_aware.py \
    --encoder_model "geolocal/StreetCLIP" \
    --batch_size 256 \
    --epochs 5 \
    --lr 3e-4 \
    --weight_decay 0.1 \
    --temperature 0.07 \
    --lambda_concept_text 1.0 \
    --lambda_concept_gps 1.0 \
    --lambda_concept 1.0 \
    --lambda_cell 1.0 \
    --lambda_offset 5.0 \
    --lambda_country 0.5 \
    --label_smoothing 0.1 \
    --early_stopping_patience 5 \
    --save_interval 1 \
    --min_samples_per_cell 20 \
    --use_wandb \
    --use_class_weights \
    --coordinate_loss_type "haversine" \
    --csv_path "/scratch-shared/pnair/Project_AI/data/dataset-43k-updated.csv" #\
    #--country_filter "India" \
    
