#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=concept_geo_neurips
#SBATCH --output=/scratch-shared/pnair/Project_AI/jobs/outputs/train_concept_geo_neurips_world_lambda_concept_10.log
#SBATCH --time=7:00:00
#SBATCH --cpus-per-task=9
#SBATCH --mem=32G

# Activate environment
module load 2025
module load Anaconda3/2025.06-1
cd /scratch-shared/pnair/Project_AI/
module load CUDA/12.8.0

source activate streetview_pnair
export PYTHONNOUSERSITE=1
export PYTHONPATH=/scratch-shared/pnair/Project_AI:$PYTHONPATH

# Run Training with NeurIPS configuration
python scripts/training/train_concept_aware.py \
    --encoder_model "geolocal/StreetCLIP" \
    --batch_size 128 \
    --epochs 5 \
    --lr 3e-4 \
    --weight_decay 0.1 \
    --temperature 0.07 \
    --lambda_concept 10.0 \
    --lambda_semantic 1.0 \
    --lambda_cell 1.0 \
    --lambda_offset 10.0 \
    --lambda_country 0.1 \
    --sigma 1.0 \
    --label_smoothing 0.1 \
    --early_stopping_patience 5 \
    --save_interval 1 \
    --min_samples_per_cell 20 \
    --use_wandb \
    --use_class_weights \
    --coordinate_loss_type "haversine" #\
    #--country_filter "India" \
    
