#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=visualize_img_per_conc
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=12:00:00
#SBATCH --mem=32GB
#SBATCH --output=jobs/outputs/visualization/visualize_cbm_%j.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/Project_AI/
source activate streetview

mkdir -p jobs/outputs/visualization
mkdir -p visualizations/concept_consistency

python scripts/visualization/visualize_concept_consistency.py

