#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=viz_saliency
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=02:00:00
#SBATCH --mem=16GB
#SBATCH --output=jobs/outputs/viz_saliency_smaller%j.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/Project_AI/
source activate streetview
pip install cv2

# Parameters
SAE_CHECKPOINT="checkpoints/sae_smaller/best_sae.pth"
DATASET_CSV="data/6921d7831744c5356b098bf7_balanced/splits/dataset_val.csv"
OUTPUT_DIR="visualizations/sae_saliency"

# Comma separated list of concepts to visualize
# Example: visualizing concepts that seemed interesting in previous steps
CONCEPTS="71, 97, 615, 712, 795, 812, 1009, 1075, 1089, 1120, 1128, 1213, 1330, 1479, 1598, 1649, 1717, 1724, 1782, 1901, 2334, 2433, 2859, 2958"  

echo "Starting Saliency Visualization for Concepts: $CONCEPTS"

python -u scripts/evaluation/visualize_saliency.py \
    --sae-path "$SAE_CHECKPOINT" \
    --csv-path "$DATASET_CSV" \
    --output-dir "$OUTPUT_DIR" \
    --concept-indices "$CONCEPTS" \
    --top-k-images 5

echo "Visualization complete. Results in $OUTPUT_DIR"

