#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=vis_sae
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=2:00:00
#SBATCH --mem=32GB
#SBATCH --output=jobs/outputs/train/visualize_sae_smallest.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/Project_AI/
source activate streetview

# Parameters
DATASET_DIR="$HOME/Project_AI/data/6921d7831744c5356b098bf7_balanced"
TRAIN_CSV="$DATASET_DIR/splits/dataset_train.csv"
VAL_CSV="$DATASET_DIR/splits/dataset_val.csv"
OUTPUT_DIR="checkpoints/sae_smallest"
VIZ_DIR="visualizations/sae_smallest"

mkdir -p jobs/outputs/train
mkdir -p $OUTPUT_DIR
mkdir -p $VIZ_DIR

echo "----------------------------------------------------------------"
echo "Job started at: $(date)"
echo "Train Dataset: $TRAIN_CSV"
echo "Val Dataset: $VAL_CSV"
echo "Output: $OUTPUT_DIR"
echo "----------------------------------------------------------------"


# 2. Visualize Concepts
# Use the BEST checkpoint
CHECKPOINT="$OUTPUT_DIR/best_sae.pth"

if [ -f "$CHECKPOINT" ]; then
    echo "Starting Concept Visualization..."
    python -u scripts/evaluation/visualize_sae_concepts.py \
        --sae-path "$CHECKPOINT" \
        --csv-path "$VAL_CSV" \
        --output-dir "$VIZ_DIR" \
        --num-concepts 20 \
        --top-k-images 9
else
    echo "Checkpoint not found, skipping visualization."
fi

echo "Job finished at: $(date)"

